AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for {{ cookiecutter.project_name }}

Globals:
  Function:
    Timeout: 60
    CodeUri: .
    Handler: swift.bootstrap
    Runtime: provided.al2
    MemorySize: 512
    Architectures:
      - {{ cookiecutter.architecture }}

Resources:
  # Lambda function
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        # handles the GET / method of the REST API
        Api:
          Type: HttpApi
          Properties:
            Method: get
            Path: /
    Metadata:
      BuildMethod: makefile

# print API endpoint and name of database table
Outputs:
  SwiftAPIEndpoint:
    Description: "API Gateway endpoint URL for your application"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"

